name: "release"

on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest

    steps:
      - name: "build"
        run: ./build.sh

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            yr32-skinbuilder.osk






